# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_HyperliquidAccount__get_positions <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_positions <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "szi", "entry_px", "position_value", "unrealized_pnl", "return_on_equity", "leverage_type", "leverage_value", "liquidation_px", "margin_used"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["szi"]])
  assert_no_missing_values(value[["szi"]])
  assert_double(value[["entry_px"]])
  assert_double(value[["position_value"]])
  assert_no_missing_values(value[["position_value"]])
  assert_double(value[["unrealized_pnl"]])
  assert_no_missing_values(value[["unrealized_pnl"]])
  assert_double(value[["return_on_equity"]])
  assert_no_missing_values(value[["return_on_equity"]])
  assert_character(value[["leverage_type"]])
  assert_no_missing_values(value[["leverage_type"]])
  assert_double(value[["leverage_value"]])
  assert_no_missing_values(value[["leverage_value"]])
  assert_double(value[["liquidation_px"]])
  assert_double(value[["margin_used"]])
  assert_no_missing_values(value[["margin_used"]])
  return(value)
}

assert_args_HyperliquidAccount__get_margin_summary <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_margin_summary <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("account_value", "total_ntl_pos", "total_raw_usd", "total_margin_used", "withdrawable", "cross_account_value", "cross_total_ntl_pos", "cross_total_raw_usd", "cross_total_margin_used"))
  assert_double(value[["account_value"]])
  assert_no_missing_values(value[["account_value"]])
  assert_double(value[["total_ntl_pos"]])
  assert_no_missing_values(value[["total_ntl_pos"]])
  assert_double(value[["total_raw_usd"]])
  assert_no_missing_values(value[["total_raw_usd"]])
  assert_double(value[["total_margin_used"]])
  assert_no_missing_values(value[["total_margin_used"]])
  assert_double(value[["withdrawable"]])
  assert_no_missing_values(value[["withdrawable"]])
  assert_double(value[["cross_account_value"]])
  assert_no_missing_values(value[["cross_account_value"]])
  assert_double(value[["cross_total_ntl_pos"]])
  assert_no_missing_values(value[["cross_total_ntl_pos"]])
  assert_double(value[["cross_total_raw_usd"]])
  assert_no_missing_values(value[["cross_total_raw_usd"]])
  assert_double(value[["cross_total_margin_used"]])
  assert_no_missing_values(value[["cross_total_margin_used"]])
  return(value)
}

assert_args_HyperliquidAccount__get_spot_balances <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_spot_balances <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "total", "hold", "entry_ntl"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["total"]])
  assert_no_missing_values(value[["total"]])
  assert_double(value[["hold"]])
  assert_no_missing_values(value[["hold"]])
  assert_double(value[["entry_ntl"]])
  assert_no_missing_values(value[["entry_ntl"]])
  return(value)
}

assert_args_HyperliquidAccount__get_open_orders <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_open_orders <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "oid", "side", "limit_px", "sz", "timestamp"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["oid"]])
  assert_no_missing_values(value[["oid"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_double(value[["limit_px"]])
  assert_no_missing_values(value[["limit_px"]])
  assert_double(value[["sz"]])
  assert_no_missing_values(value[["sz"]])
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  return(value)
}

assert_args_HyperliquidAccount__get_frontend_open_orders <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_frontend_open_orders <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "oid", "side", "limit_px", "sz", "timestamp", "order_type", "is_trigger", "trigger_px", "trigger_condition", "reduce_only", "tif", "orig_sz", "is_position_tpsl"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["oid"]])
  assert_no_missing_values(value[["oid"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_double(value[["limit_px"]])
  assert_no_missing_values(value[["limit_px"]])
  assert_double(value[["sz"]])
  assert_no_missing_values(value[["sz"]])
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_character(value[["order_type"]])
  assert_no_missing_values(value[["order_type"]])
  assert_logical(value[["is_trigger"]])
  assert_no_missing_values(value[["is_trigger"]])
  assert_double(value[["trigger_px"]])
  assert_no_missing_values(value[["trigger_px"]])
  assert_character(value[["trigger_condition"]])
  assert_no_missing_values(value[["trigger_condition"]])
  assert_logical(value[["reduce_only"]])
  assert_no_missing_values(value[["reduce_only"]])
  assert_character(value[["tif"]])
  assert_double(value[["orig_sz"]])
  assert_no_missing_values(value[["orig_sz"]])
  assert_logical(value[["is_position_tpsl"]])
  assert_no_missing_values(value[["is_position_tpsl"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_fills <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_fills <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "px", "sz", "side", "time", "start_position", "dir", "closed_pnl", "hash", "oid", "crossed", "fee", "fee_token", "tid"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["px"]])
  assert_no_missing_values(value[["px"]])
  assert_double(value[["sz"]])
  assert_no_missing_values(value[["sz"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_double(value[["start_position"]])
  assert_no_missing_values(value[["start_position"]])
  assert_character(value[["dir"]])
  assert_no_missing_values(value[["dir"]])
  assert_double(value[["closed_pnl"]])
  assert_no_missing_values(value[["closed_pnl"]])
  assert_character(value[["hash"]])
  assert_no_missing_values(value[["hash"]])
  assert_double(value[["oid"]])
  assert_no_missing_values(value[["oid"]])
  assert_logical(value[["crossed"]])
  assert_no_missing_values(value[["crossed"]])
  assert_double(value[["fee"]])
  assert_no_missing_values(value[["fee"]])
  assert_character(value[["fee_token"]])
  assert_no_missing_values(value[["fee_token"]])
  assert_double(value[["tid"]])
  assert_no_missing_values(value[["tid"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_fills_by_time <- function(address, start, end, aggregate_by_time) {
  assert_scalar_character(address)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  if (!is.null(end)) {
    assert_any_of(
      end,
      function(.x) {
        assert_datetime(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_double(.x)
        assert_no_missing_values(.x)
      }
    )
  }
  assert_scalar_logical(aggregate_by_time)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_fills_by_time <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "px", "sz", "side", "time", "start_position", "dir", "closed_pnl", "hash", "oid", "crossed", "fee", "fee_token", "tid"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["px"]])
  assert_no_missing_values(value[["px"]])
  assert_double(value[["sz"]])
  assert_no_missing_values(value[["sz"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_double(value[["start_position"]])
  assert_no_missing_values(value[["start_position"]])
  assert_character(value[["dir"]])
  assert_no_missing_values(value[["dir"]])
  assert_double(value[["closed_pnl"]])
  assert_no_missing_values(value[["closed_pnl"]])
  assert_character(value[["hash"]])
  assert_no_missing_values(value[["hash"]])
  assert_double(value[["oid"]])
  assert_no_missing_values(value[["oid"]])
  assert_logical(value[["crossed"]])
  assert_no_missing_values(value[["crossed"]])
  assert_double(value[["fee"]])
  assert_no_missing_values(value[["fee"]])
  assert_character(value[["fee_token"]])
  assert_no_missing_values(value[["fee_token"]])
  assert_double(value[["tid"]])
  assert_no_missing_values(value[["tid"]])
  return(value)
}

assert_args_HyperliquidAccount__get_historical_orders <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_historical_orders <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("oid", "coin", "side", "limit_px", "sz", "orig_sz", "order_type", "tif", "reduce_only", "trigger_px", "trigger_condition", "is_trigger", "is_position_tpsl", "cloid", "timestamp", "status", "status_timestamp"))
  assert_double(value[["oid"]])
  assert_no_missing_values(value[["oid"]])
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_double(value[["limit_px"]])
  assert_no_missing_values(value[["limit_px"]])
  assert_double(value[["sz"]])
  assert_no_missing_values(value[["sz"]])
  assert_double(value[["orig_sz"]])
  assert_no_missing_values(value[["orig_sz"]])
  assert_character(value[["order_type"]])
  assert_no_missing_values(value[["order_type"]])
  assert_character(value[["tif"]])
  assert_logical(value[["reduce_only"]])
  assert_no_missing_values(value[["reduce_only"]])
  assert_double(value[["trigger_px"]])
  assert_no_missing_values(value[["trigger_px"]])
  assert_character(value[["trigger_condition"]])
  assert_no_missing_values(value[["trigger_condition"]])
  assert_logical(value[["is_trigger"]])
  assert_no_missing_values(value[["is_trigger"]])
  assert_logical(value[["is_position_tpsl"]])
  assert_no_missing_values(value[["is_position_tpsl"]])
  assert_character(value[["cloid"]])
  assert_datetime(value[["timestamp"]])
  assert_no_missing_values(value[["timestamp"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_datetime(value[["status_timestamp"]])
  assert_no_missing_values(value[["status_timestamp"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_funding <- function(address, start, end) {
  assert_scalar_character(address)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  if (!is.null(end)) {
    assert_any_of(
      end,
      function(.x) {
        assert_datetime(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_double(.x)
        assert_no_missing_values(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_funding <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("time", "hash", "coin", "funding_rate", "szi", "usdc", "n_samples"))
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_character(value[["hash"]])
  assert_no_missing_values(value[["hash"]])
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["funding_rate"]])
  assert_no_missing_values(value[["funding_rate"]])
  assert_double(value[["szi"]])
  assert_no_missing_values(value[["szi"]])
  assert_double(value[["usdc"]])
  assert_no_missing_values(value[["usdc"]])
  assert_double(value[["n_samples"]])
  assert_no_missing_values(value[["n_samples"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_non_funding_ledger_updates <- function(address, start, end) {
  assert_scalar_character(address)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  if (!is.null(end)) {
    assert_any_of(
      end,
      function(.x) {
        assert_datetime(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_double(.x)
        assert_no_missing_values(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_non_funding_ledger_updates <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_HyperliquidAccount__get_portfolio <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_portfolio <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("period", "metric", "time", "value"))
  assert_character(value[["period"]])
  assert_no_missing_values(value[["period"]])
  assert_character(value[["metric"]])
  assert_no_missing_values(value[["metric"]])
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_double(value[["value"]])
  assert_no_missing_values(value[["value"]])
  return(value)
}

assert_args_HyperliquidAccount__get_portfolio_volume <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_portfolio_volume <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("period", "vlm"))
  assert_character(value[["period"]])
  assert_no_missing_values(value[["period"]])
  assert_double(value[["vlm"]])
  assert_no_missing_values(value[["vlm"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_fees <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_fees <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("user_add_rate", "user_cross_rate", "active_referral_discount"))
  assert_double(value[["user_add_rate"]])
  assert_no_missing_values(value[["user_add_rate"]])
  assert_double(value[["user_cross_rate"]])
  assert_no_missing_values(value[["user_cross_rate"]])
  assert_double(value[["active_referral_discount"]])
  assert_no_missing_values(value[["active_referral_discount"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_volume <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_volume <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("date", "exchange", "user_add", "user_cross"))
  assert_character(value[["date"]])
  assert_no_missing_values(value[["date"]])
  assert_double(value[["exchange"]])
  assert_no_missing_values(value[["exchange"]])
  assert_double(value[["user_add"]])
  assert_no_missing_values(value[["user_add"]])
  assert_double(value[["user_cross"]])
  assert_no_missing_values(value[["user_cross"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_rate_limit <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_rate_limit <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("cum_vlm", "n_requests_used", "n_requests_cap"))
  assert_double(value[["cum_vlm"]])
  assert_no_missing_values(value[["cum_vlm"]])
  assert_double(value[["n_requests_used"]])
  assert_no_missing_values(value[["n_requests_used"]])
  assert_double(value[["n_requests_cap"]])
  assert_no_missing_values(value[["n_requests_cap"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_role <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_role <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("role"))
  assert_character(value[["role"]])
  assert_no_missing_values(value[["role"]])
  return(value)
}

assert_args_HyperliquidAccount__get_sub_accounts <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_sub_accounts <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "sub_account_user", "master", "account_value", "total_ntl_pos", "total_raw_usd", "total_margin_used", "withdrawable"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["sub_account_user"]])
  assert_no_missing_values(value[["sub_account_user"]])
  assert_character(value[["master"]])
  assert_no_missing_values(value[["master"]])
  assert_double(value[["account_value"]])
  assert_no_missing_values(value[["account_value"]])
  assert_double(value[["total_ntl_pos"]])
  assert_no_missing_values(value[["total_ntl_pos"]])
  assert_double(value[["total_raw_usd"]])
  assert_no_missing_values(value[["total_raw_usd"]])
  assert_double(value[["total_margin_used"]])
  assert_no_missing_values(value[["total_margin_used"]])
  assert_double(value[["withdrawable"]])
  assert_no_missing_values(value[["withdrawable"]])
  return(value)
}

assert_args_HyperliquidAccount__get_order_status <- function(address, oid_or_cloid) {
  assert_scalar_character(address)
  assert_any_of(
    oid_or_cloid,
    function(.x) {
      assert_scalar_double(.x)
    },
    function(.x) {
      assert_scalar_character(.x)
    }
  )
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_order_status <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("query_status", "oid", "coin", "side", "limit_px", "sz", "orig_sz", "order_type", "tif", "reduce_only", "trigger_px", "trigger_condition", "is_trigger", "is_position_tpsl", "cloid", "timestamp", "status", "status_timestamp"))
  assert_character(value[["query_status"]])
  assert_no_missing_values(value[["query_status"]])
  assert_double(value[["oid"]])
  assert_character(value[["coin"]])
  assert_character(value[["side"]])
  assert_double(value[["limit_px"]])
  assert_double(value[["sz"]])
  assert_double(value[["orig_sz"]])
  assert_character(value[["order_type"]])
  assert_character(value[["tif"]])
  assert_logical(value[["reduce_only"]])
  assert_double(value[["trigger_px"]])
  assert_character(value[["trigger_condition"]])
  assert_logical(value[["is_trigger"]])
  assert_logical(value[["is_position_tpsl"]])
  assert_character(value[["cloid"]])
  assert_datetime(value[["timestamp"]])
  assert_character(value[["status"]])
  assert_datetime(value[["status_timestamp"]])
  return(value)
}

assert_args_HyperliquidAccount__get_user_vault_equities <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidAccount__get_user_vault_equities <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("vault_address", "equity", "locked_until_timestamp"))
  assert_character(value[["vault_address"]])
  assert_no_missing_values(value[["vault_address"]])
  assert_double(value[["equity"]])
  assert_no_missing_values(value[["equity"]])
  assert_datetime(value[["locked_until_timestamp"]])
  assert_no_missing_values(value[["locked_until_timestamp"]])
  return(value)
}

assert_args_HyperliquidBase__initialize <- function(keys, testnet, async, vault_address) {
  assert_list(keys)
  assert_scalar_logical(testnet)
  assert_scalar_logical(async)
  if (!is.null(vault_address)) {
    assert_scalar_character(vault_address)
  }
  return(invisible(NULL))
}

assert_return_HyperliquidBase__initialize <- function(value) {
  assert_class(value, "HyperliquidBase")
  return(value)
}

assert_return_HyperliquidBase__refresh_meta <- function(value) {
  assert_class(value, "HyperliquidBase")
  return(value)
}

assert_args_HyperliquidBase__name_to_asset <- function(name) {
  assert_scalar_character(name)
  return(invisible(NULL))
}

assert_return_HyperliquidBase__name_to_asset <- function(value) {
  assert_scalar_count(value)
  return(value)
}

assert_args_HyperliquidBase__name_to_coin <- function(name) {
  assert_scalar_character(name)
  return(invisible(NULL))
}

assert_return_HyperliquidBase__name_to_coin <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_HyperliquidBase__sz_decimals <- function(asset) {
  assert_scalar_count(asset)
  return(invisible(NULL))
}

assert_return_HyperliquidBase__sz_decimals <- function(value) {
  assert_scalar_count(value)
  return(value)
}

assert_return_HyperliquidMarketData__get_meta <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "sz_decimals", "max_leverage", "margin_table_id", "only_isolated", "is_delisted", "margin_mode"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_double(value[["sz_decimals"]])
  assert_no_missing_values(value[["sz_decimals"]])
  assert_double(value[["max_leverage"]])
  assert_no_missing_values(value[["max_leverage"]])
  assert_double(value[["margin_table_id"]])
  assert_no_missing_values(value[["margin_table_id"]])
  assert_logical(value[["only_isolated"]])
  assert_logical(value[["is_delisted"]])
  assert_no_missing_values(value[["is_delisted"]])
  assert_character(value[["margin_mode"]])
  return(value)
}

assert_return_HyperliquidMarketData__get_spot_meta <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "index", "is_canonical", "token_base", "token_quote"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_double(value[["index"]])
  assert_no_missing_values(value[["index"]])
  assert_logical(value[["is_canonical"]])
  assert_no_missing_values(value[["is_canonical"]])
  assert_double(value[["token_base"]])
  assert_no_missing_values(value[["token_base"]])
  assert_double(value[["token_quote"]])
  assert_no_missing_values(value[["token_quote"]])
  return(value)
}

assert_return_HyperliquidMarketData__get_spot_tokens <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "index", "sz_decimals", "wei_decimals", "token_id", "is_canonical"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_double(value[["index"]])
  assert_no_missing_values(value[["index"]])
  assert_double(value[["sz_decimals"]])
  assert_no_missing_values(value[["sz_decimals"]])
  assert_double(value[["wei_decimals"]])
  assert_no_missing_values(value[["wei_decimals"]])
  assert_character(value[["token_id"]])
  assert_no_missing_values(value[["token_id"]])
  assert_logical(value[["is_canonical"]])
  assert_no_missing_values(value[["is_canonical"]])
  return(value)
}

assert_return_HyperliquidMarketData__get_meta_and_asset_ctxs <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "sz_decimals", "max_leverage", "day_ntl_vlm", "funding", "mark_px", "mid_px", "oracle_px", "open_interest", "premium", "prev_day_px", "impact_px_bid", "impact_px_ask"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_double(value[["sz_decimals"]])
  assert_no_missing_values(value[["sz_decimals"]])
  assert_double(value[["max_leverage"]])
  assert_no_missing_values(value[["max_leverage"]])
  assert_double(value[["day_ntl_vlm"]])
  assert_double(value[["funding"]])
  assert_double(value[["mark_px"]])
  assert_double(value[["mid_px"]])
  assert_double(value[["oracle_px"]])
  assert_double(value[["open_interest"]])
  assert_double(value[["premium"]])
  assert_double(value[["prev_day_px"]])
  assert_double(value[["impact_px_bid"]])
  assert_double(value[["impact_px_ask"]])
  return(value)
}

assert_return_HyperliquidMarketData__get_spot_meta_and_asset_ctxs <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "day_ntl_vlm", "mark_px", "mid_px", "prev_day_px", "circulating_supply"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["day_ntl_vlm"]])
  assert_no_missing_values(value[["day_ntl_vlm"]])
  assert_double(value[["mark_px"]])
  assert_no_missing_values(value[["mark_px"]])
  assert_double(value[["mid_px"]])
  assert_double(value[["prev_day_px"]])
  assert_no_missing_values(value[["prev_day_px"]])
  assert_double(value[["circulating_supply"]])
  assert_no_missing_values(value[["circulating_supply"]])
  return(value)
}

assert_return_HyperliquidMarketData__get_all_mids <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "mid"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["mid"]])
  assert_no_missing_values(value[["mid"]])
  return(value)
}

assert_args_HyperliquidMarketData__get_l2_book <- function(coin, n_sig_figs, mantissa) {
  assert_scalar_character(coin)
  if (!is.null(n_sig_figs)) {
    assert_scalar_double(n_sig_figs)
  }
  if (!is.null(mantissa)) {
    assert_scalar_double(mantissa)
  }
  return(invisible(NULL))
}

assert_return_HyperliquidMarketData__get_l2_book <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("side", "level", "px", "sz", "n"))
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_integer(value[["level"]])
  assert_no_missing_values(value[["level"]])
  assert_double(value[["px"]])
  assert_no_missing_values(value[["px"]])
  assert_double(value[["sz"]])
  assert_no_missing_values(value[["sz"]])
  assert_double(value[["n"]])
  assert_no_missing_values(value[["n"]])
  return(value)
}

assert_args_HyperliquidMarketData__get_candles <- function(coin, interval, start, end) {
  assert_scalar_character(coin)
  assert_scalar_character(interval)
  assert_value_in_set(interval, HYPERLIQUID_INTERVALS)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    end,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  return(invisible(NULL))
}

assert_return_HyperliquidMarketData__get_candles <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("datetime", "open", "high", "low", "close", "volume", "trades", "close_time", "interval", "coin"))
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  assert_double(value[["volume"]])
  assert_no_missing_values(value[["volume"]])
  assert_double(value[["trades"]])
  assert_no_missing_values(value[["trades"]])
  assert_datetime(value[["close_time"]])
  assert_no_missing_values(value[["close_time"]])
  assert_character(value[["interval"]])
  assert_no_missing_values(value[["interval"]])
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  return(value)
}

assert_args_HyperliquidMarketData__get_funding_history <- function(coin, start, end) {
  assert_scalar_character(coin)
  assert_any_of(
    start,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  if (!is.null(end)) {
    assert_any_of(
      end,
      function(.x) {
        assert_datetime(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_double(.x)
        assert_no_missing_values(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_HyperliquidMarketData__get_funding_history <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "funding_rate", "premium", "time"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["funding_rate"]])
  assert_no_missing_values(value[["funding_rate"]])
  assert_double(value[["premium"]])
  assert_no_missing_values(value[["premium"]])
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  return(value)
}

assert_return_HyperliquidMarketData__get_predicted_fundings <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "venue", "funding_rate", "next_funding_time", "funding_interval_hours"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_character(value[["venue"]])
  assert_no_missing_values(value[["venue"]])
  assert_double(value[["funding_rate"]])
  assert_datetime(value[["next_funding_time"]])
  assert_double(value[["funding_interval_hours"]])
  return(value)
}

assert_return_HyperliquidMarketData__get_perp_dexs <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("name", "full_name", "deployer", "oracle_updater", "fee_recipient"))
  assert_character(value[["name"]])
  assert_no_missing_values(value[["name"]])
  assert_character(value[["full_name"]])
  assert_no_missing_values(value[["full_name"]])
  assert_character(value[["deployer"]])
  assert_no_missing_values(value[["deployer"]])
  assert_character(value[["oracle_updater"]])
  assert_character(value[["fee_recipient"]])
  assert_no_missing_values(value[["fee_recipient"]])
  return(value)
}

assert_args_HyperliquidMarketData__get_recent_trades <- function(coin) {
  assert_scalar_character(coin)
  return(invisible(NULL))
}

assert_return_HyperliquidMarketData__get_recent_trades <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "side", "px", "sz", "time", "hash", "tid", "user_buyer", "user_seller"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_double(value[["px"]])
  assert_no_missing_values(value[["px"]])
  assert_double(value[["sz"]])
  assert_no_missing_values(value[["sz"]])
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_character(value[["hash"]])
  assert_no_missing_values(value[["hash"]])
  assert_double(value[["tid"]])
  assert_no_missing_values(value[["tid"]])
  assert_character(value[["user_buyer"]])
  assert_no_missing_values(value[["user_buyer"]])
  assert_character(value[["user_seller"]])
  assert_no_missing_values(value[["user_seller"]])
  return(value)
}

assert_return_HyperliquidMarketData__get_exchange_status <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("time", "special_statuses"))
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_character(value[["special_statuses"]])
  return(value)
}

assert_args_HyperliquidStaking__get_staking_summary <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidStaking__get_staking_summary <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("delegated", "undelegated", "total_pending_withdrawal", "n_pending_withdrawals"))
  assert_double(value[["delegated"]])
  assert_no_missing_values(value[["delegated"]])
  assert_double(value[["undelegated"]])
  assert_no_missing_values(value[["undelegated"]])
  assert_double(value[["total_pending_withdrawal"]])
  assert_no_missing_values(value[["total_pending_withdrawal"]])
  assert_integer(value[["n_pending_withdrawals"]])
  return(value)
}

assert_args_HyperliquidStaking__get_staking_delegations <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidStaking__get_staking_delegations <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("validator", "amount", "locked_until_timestamp"))
  assert_character(value[["validator"]])
  assert_no_missing_values(value[["validator"]])
  assert_double(value[["amount"]])
  assert_no_missing_values(value[["amount"]])
  assert_datetime(value[["locked_until_timestamp"]])
  assert_no_missing_values(value[["locked_until_timestamp"]])
  return(value)
}

assert_args_HyperliquidStaking__get_staking_rewards <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidStaking__get_staking_rewards <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("time", "source", "total_amount"))
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  assert_character(value[["source"]])
  assert_no_missing_values(value[["source"]])
  assert_double(value[["total_amount"]])
  assert_no_missing_values(value[["total_amount"]])
  return(value)
}

assert_args_HyperliquidStaking__get_delegator_history <- function(address) {
  assert_scalar_character(address)
  return(invisible(NULL))
}

assert_return_HyperliquidStaking__get_delegator_history <- function(value) {
  assert_data_table(value)
  return(value)
}

assert_args_HyperliquidStaking__token_delegate <- function(validator, wei, is_undelegate) {
  assert_scalar_character(validator)
  assert_scalar_double(wei)
  assert_between(wei, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(is_undelegate)
  return(invisible(NULL))
}

assert_return_HyperliquidStaking__token_delegate <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTrading__place_order <- function(name, is_buy, sz, limit_px, order_type, reduce_only, cloid, builder) {
  assert_scalar_character(name)
  assert_scalar_logical(is_buy)
  assert_scalar_double(sz)
  assert_between(sz, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_double(limit_px)
  assert_between(limit_px, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_list(order_type)
  assert_scalar_logical(reduce_only)
  if (!is.null(cloid)) {
    assert_scalar_character(cloid)
  }
  if (!is.null(builder)) {
    assert_list(builder)
  }
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__place_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "oid", "total_sz", "avg_px", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_double(value[["oid"]])
  assert_double(value[["total_sz"]])
  assert_double(value[["avg_px"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__bulk_orders <- function(orders, builder, grouping) {
  assert_list(orders)
  if (!is.null(builder)) {
    assert_list(builder)
  }
  assert_scalar_character(grouping)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__bulk_orders <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "oid", "total_sz", "avg_px", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_double(value[["oid"]])
  assert_double(value[["total_sz"]])
  assert_double(value[["avg_px"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__market_open <- function(name, is_buy, sz, slippage, cloid, builder) {
  assert_scalar_character(name)
  assert_scalar_logical(is_buy)
  assert_scalar_double(sz)
  assert_between(sz, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_double(slippage)
  assert_between(slippage, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  if (!is.null(cloid)) {
    assert_scalar_character(cloid)
  }
  if (!is.null(builder)) {
    assert_list(builder)
  }
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__market_open <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "oid", "total_sz", "avg_px", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_double(value[["oid"]])
  assert_double(value[["total_sz"]])
  assert_double(value[["avg_px"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__market_close <- function(name, sz, slippage, cloid) {
  assert_scalar_character(name)
  if (!is.null(sz)) {
    assert_scalar_double(sz)
    assert_between(sz, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  }
  assert_scalar_double(slippage)
  assert_between(slippage, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  if (!is.null(cloid)) {
    assert_scalar_character(cloid)
  }
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__market_close <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "oid", "total_sz", "avg_px", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_double(value[["oid"]])
  assert_double(value[["total_sz"]])
  assert_double(value[["avg_px"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__modify_order <- function(oid, name, is_buy, sz, limit_px, order_type, reduce_only, cloid) {
  assert_scalar_double(oid)
  assert_scalar_character(name)
  assert_scalar_logical(is_buy)
  assert_scalar_double(sz)
  assert_between(sz, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_double(limit_px)
  assert_between(limit_px, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_list(order_type)
  assert_scalar_logical(reduce_only)
  if (!is.null(cloid)) {
    assert_scalar_character(cloid)
  }
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__modify_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "oid", "total_sz", "avg_px", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_double(value[["oid"]])
  assert_double(value[["total_sz"]])
  assert_double(value[["avg_px"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__bulk_modify <- function(modifies) {
  assert_list(modifies)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__bulk_modify <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "oid", "total_sz", "avg_px", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_double(value[["oid"]])
  assert_double(value[["total_sz"]])
  assert_double(value[["avg_px"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__cancel_order <- function(name, oid) {
  assert_scalar_character(name)
  assert_scalar_double(oid)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__cancel_order <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__cancel_by_cloid <- function(name, cloid) {
  assert_scalar_character(name)
  assert_scalar_character(cloid)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__cancel_by_cloid <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__bulk_cancel <- function(cancels) {
  assert_list(cancels)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__bulk_cancel <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__bulk_cancel_by_cloid <- function(cancels) {
  assert_list(cancels)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__bulk_cancel_by_cloid <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "error"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["error"]])
  return(value)
}

assert_args_HyperliquidTrading__schedule_cancel <- function(time) {
  if (!is.null(time)) {
    assert_any_of(
      time,
      function(.x) {
        assert_datetime(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_double(.x)
        assert_no_missing_values(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__schedule_cancel <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTrading__update_leverage <- function(name, leverage, is_cross) {
  assert_scalar_character(name)
  assert_scalar_count(leverage)
  assert_between(leverage, lower = 1)
  assert_scalar_logical(is_cross)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__update_leverage <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTrading__update_isolated_margin <- function(name, amount) {
  assert_scalar_character(name)
  assert_scalar_double(amount)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__update_isolated_margin <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTrading__approve_agent <- function(name) {
  if (!is.null(name)) {
    assert_scalar_character(name)
  }
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__approve_agent <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("agent_address", "agent_key", "status"))
  assert_character(value[["agent_address"]])
  assert_no_missing_values(value[["agent_address"]])
  assert_character(value[["agent_key"]])
  assert_no_missing_values(value[["agent_key"]])
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  return(value)
}

assert_args_HyperliquidTrading__approve_builder_fee <- function(builder, max_fee_rate) {
  assert_scalar_character(builder)
  assert_scalar_character(max_fee_rate)
  return(invisible(NULL))
}

assert_return_HyperliquidTrading__approve_builder_fee <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTransfers__usd_class_transfer <- function(amount, to_perp) {
  assert_scalar_double(amount)
  assert_between(amount, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(to_perp)
  return(invisible(NULL))
}

assert_return_HyperliquidTransfers__usd_class_transfer <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTransfers__usd_send <- function(amount, destination) {
  assert_scalar_double(amount)
  assert_between(amount, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_character(destination)
  return(invisible(NULL))
}

assert_return_HyperliquidTransfers__usd_send <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTransfers__spot_send <- function(amount, destination, token) {
  assert_scalar_double(amount)
  assert_between(amount, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_character(destination)
  assert_scalar_character(token)
  return(invisible(NULL))
}

assert_return_HyperliquidTransfers__spot_send <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTransfers__withdraw <- function(amount, destination) {
  assert_scalar_double(amount)
  assert_between(amount, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_character(destination)
  return(invisible(NULL))
}

assert_return_HyperliquidTransfers__withdraw <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTransfers__send_asset <- function(destination, source_dex, destination_dex, token, amount) {
  assert_scalar_character(destination)
  assert_scalar_character(source_dex)
  assert_scalar_character(destination_dex)
  assert_scalar_character(token)
  assert_scalar_double(amount)
  assert_between(amount, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_HyperliquidTransfers__send_asset <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTransfers__sub_account_transfer <- function(sub_account_user, is_deposit, usd) {
  assert_scalar_character(sub_account_user)
  assert_scalar_logical(is_deposit)
  assert_scalar_double(usd)
  assert_between(usd, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_HyperliquidTransfers__sub_account_transfer <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTransfers__sub_account_spot_transfer <- function(sub_account_user, is_deposit, token, amount) {
  assert_scalar_character(sub_account_user)
  assert_scalar_logical(is_deposit)
  assert_scalar_character(token)
  assert_scalar_double(amount)
  assert_between(amount, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_HyperliquidTransfers__sub_account_spot_transfer <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_HyperliquidTransfers__vault_transfer <- function(vault_address, is_deposit, usd) {
  assert_scalar_character(vault_address)
  assert_scalar_logical(is_deposit)
  assert_scalar_double(usd)
  assert_between(usd, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_HyperliquidTransfers__vault_transfer <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("status", "response_type"))
  assert_character(value[["status"]])
  assert_no_missing_values(value[["status"]])
  assert_character(value[["response_type"]])
  assert_no_missing_values(value[["response_type"]])
  return(value)
}

assert_args_hyperliquid_backfill_klines <- function(symbols, intervals, from, to, file, testnet, sleep, verbose) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_character(intervals)
  assert_no_missing_values(intervals)
  assert_values_in_set(intervals, HYPERLIQUID_INTERVALS)
  assert_any_of(
    from,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    to,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_scalar_character(file)
  assert_scalar_logical(testnet)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(verbose)
  return(invisible(NULL))
}

assert_return_hyperliquid_backfill_klines <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_hyperliquid_fetch_funding <- function(coin, from, to, .req_fn, page_limit, sleep) {
  assert_scalar_character(coin)
  assert_any_of(
    from,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    to,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_function(.req_fn)
  assert_scalar_integer(page_limit)
  assert_between(page_limit, lower = 1)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_hyperliquid_fetch_funding <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("coin", "funding_rate", "premium", "time"))
  assert_character(value[["coin"]])
  assert_no_missing_values(value[["coin"]])
  assert_double(value[["funding_rate"]])
  assert_no_missing_values(value[["funding_rate"]])
  assert_double(value[["premium"]])
  assert_no_missing_values(value[["premium"]])
  assert_datetime(value[["time"]])
  assert_no_missing_values(value[["time"]])
  return(value)
}

assert_args_hyperliquid_backfill_funding <- function(symbols, from, to, file, testnet, sleep, verbose) {
  assert_character(symbols)
  assert_no_missing_values(symbols)
  assert_any_of(
    from,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_any_of(
    to,
    function(.x) {
      assert_datetime(.x)
      assert_no_missing_values(.x)
    },
    function(.x) {
      assert_double(.x)
      assert_no_missing_values(.x)
    }
  )
  assert_scalar_character(file)
  assert_scalar_logical(testnet)
  assert_scalar_double(sleep)
  assert_between(sleep, lower = 0, upper = Inf, upper_inclusive = FALSE)
  assert_scalar_logical(verbose)
  return(invisible(NULL))
}

assert_return_hyperliquid_backfill_funding <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_hyperliquid_build_request <- function(base_url, path, body, .perform, .parser, is_async, timeout, parse_envelope) {
  assert_scalar_character(base_url)
  assert_scalar_character(path)
  assert_list(body)
  assert_function(.perform)
  assert_function(.parser)
  assert_scalar_logical(is_async)
  assert_scalar_double(timeout)
  assert_between(timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  assert_function(parse_envelope)
  return(invisible(NULL))
}

assert_return_hyperliquid_build_request <- function(value) {
  return(value)
}

assert_args_parse_hyperliquid_response <- function(resp) {
  assert_class(resp, "httr2_response")
  return(invisible(NULL))
}

assert_return_parse_hyperliquid_response <- function(value) {
  if (!is.null(value)) {
    assert_list(value)
  }
  return(value)
}

assert_args_build_asset_maps <- function(meta, spot_meta) {
  assert_list(meta)
  assert_list(spot_meta)
  return(invisible(NULL))
}

assert_return_build_asset_maps <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_meta_name_to_coin <- function(maps, name) {
  assert_list(maps)
  assert_scalar_character(name)
  return(invisible(NULL))
}

assert_return_meta_name_to_coin <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_meta_name_to_asset <- function(maps, name) {
  assert_list(maps)
  assert_scalar_character(name)
  return(invisible(NULL))
}

assert_return_meta_name_to_asset <- function(value) {
  assert_scalar_count(value)
  return(value)
}

assert_args_meta_sz_decimals <- function(maps, asset) {
  assert_list(maps)
  assert_scalar_count(asset)
  return(invisible(NULL))
}

assert_return_meta_sz_decimals <- function(value) {
  assert_scalar_count(value)
  return(value)
}

assert_args_get_base_url <- function(testnet) {
  assert_scalar_logical(testnet)
  return(invisible(NULL))
}

assert_return_get_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_return_new_cloid <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_normalise_private_key <- function(private_key) {
  assert_scalar_character(private_key)
  return(invisible(NULL))
}

assert_return_normalise_private_key <- function(value) {
  assert_raw(value)
  assert_length(value, 32L)
  return(value)
}

assert_args_get_api_keys <- function(private_key, account_address) {
  assert_scalar_character(private_key)
  assert_scalar_character(account_address)
  return(invisible(NULL))
}

assert_return_get_api_keys <- function(value) {
  assert_list(value)
  assert_has_names(value, c("private_key", "account_address", "wallet_address"))
  if (!is.null(value[["private_key"]])) {
    assert_raw(value[["private_key"]])
    assert_length(value[["private_key"]], 32L)
  }
  if (!is.null(value[["account_address"]])) {
    assert_scalar_character(value[["account_address"]])
  }
  if (!is.null(value[["wallet_address"]])) {
    assert_scalar_character(value[["wallet_address"]])
  }
  return(value)
}

assert_args_ms_to_datetime <- function(x) {
  assert_double(x)
  return(invisible(NULL))
}

assert_return_ms_to_datetime <- function(value) {
  assert_datetime(value)
  return(value)
}

assert_args_datetime_to_ms <- function(x) {
  if (!is.null(x)) {
    assert_any_of(
      x,
      function(.x) {
        assert_datetime(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_date(.x)
        assert_no_missing_values(.x)
      },
      function(.x) {
        assert_double(.x)
        assert_no_missing_values(.x)
      }
    )
  }
  return(invisible(NULL))
}

assert_return_datetime_to_ms <- function(value) {
  if (!is.null(value)) {
    assert_double(value)
    assert_no_missing_values(value)
  }
  return(value)
}

assert_args_time_convert_from_hyperliquid <- function(time_value) {
  assert_double(time_value)
  assert_no_missing_values(time_value)
  return(invisible(NULL))
}

assert_return_time_convert_from_hyperliquid <- function(value) {
  assert_datetime(value)
  assert_no_missing_values(value)
  return(value)
}

assert_args_time_convert_to_hyperliquid <- function(datetime) {
  assert_datetime(datetime)
  assert_no_missing_values(datetime)
  return(invisible(NULL))
}

assert_return_time_convert_to_hyperliquid <- function(value) {
  assert_double(value)
  assert_no_missing_values(value)
  return(value)
}

